version: '3.8'
services:
  db:
    restart: 'always'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=lucid"
      - "POSTGRES_PASSWORD=1234"
    volumes:
      - /tmp/postgresdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    image: 'postgres'

  currency-app:
    restart: 'always'
    ports:
      - '3333:3333'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'db'
